version: "3"
services:
   database:
     container_name: mongodatabase
     image: mongo
     ports:
        - "27017:27017"
     environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
     volumes:
        - .:/data/db 
     logging:
       driver: none
     networks:
        - node-network
   
   web:
     container_name: nodeapp
     restart: always
     build: .
     ports:
        - "4000:8443"
        - "8001:8000" 
     links:
        - database
     depends_on:
        - database
     volumes:
        - .:/usr/src/app
     networks:
        - node-network  
 

networks:
  node-network:
    driver: bridge